on: push
env:
  PORT: 8080
  ACCESS_TOKEN_SECRET: somesecret1
  REFRESH_TOKEN_SECRET: somesecret2
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:18
    steps: 
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run start